import copy

BP_MANIFEST = {
  "format_version": 2,
  "header": {"name":"{{PACK_NAME}} BP","description":"{{PACK_DESCRIPTION}}","uuid":"{{BP_UUID_HEADER}}","version":[1,0,0],"min_engine_version":[1,20,0]},
  "modules": [{"type":"data","uuid":"{{BP_UUID_MODULE}}","version":[1,0,0]}],
  "dependencies": [{"uuid":"{{RP_UUID_HEADER}}","version":[1,0,0]}]
}
RP_MANIFEST = {
  "format_version": 2,
  "header": {"name":"{{PACK_NAME}} RP","description":"{{PACK_DESCRIPTION}}","uuid":"{{RP_UUID_HEADER}}","version":[1,0,0],"min_engine_version":[1,20,0]},
  "modules": [{"type":"resources","uuid":"{{RP_UUID_MODULE}}","version":[1,0,0]}],
  "dependencies": [{"uuid":"{{BP_UUID_HEADER}}","version":[1,0,0]}]
}
SWORD = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Equipment"},"components":{"minecraft:hand_equipped":True,"minecraft:max_stack_size":1,"minecraft:durability":{"max_durability":"{{DURABILITY}}"},"minecraft:damage":"{{DAMAGE}}","minecraft:enchantable":{"value":10,"slot":"sword"},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}},"events":"{{EVENTS}}"}}
AXE = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Equipment"},"components":{"minecraft:hand_equipped":True,"minecraft:max_stack_size":1,"minecraft:durability":{"max_durability":"{{DURABILITY}}"},"minecraft:damage":"{{DAMAGE}}","minecraft:enchantable":{"value":10,"slot":"axe"},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}}}}
BOW = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Equipment"},"components":{"minecraft:hand_equipped":True,"minecraft:max_stack_size":1,"minecraft:durability":{"max_durability":"{{DURABILITY}}"},"minecraft:enchantable":{"value":1,"slot":"bow"},"minecraft:shooter":{"ammunition":[{"item":"minecraft:arrow","use_offhand":True,"search_inventory":True}],"max_draw_duration":"{{DRAW_DURATION}}","scale_power_by_draw_duration":True},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}}}}
FOOD = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Items"},"components":{"minecraft:max_stack_size":"{{STACK_SIZE}}","minecraft:food":{"nutrition":"{{NUTRITION}}","saturation_modifier":"{{SATURATION}}","can_always_eat":"{{CAN_ALWAYS_EAT}}","effects":"{{FOOD_EFFECTS}}"},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}}}}
POTION = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Items"},"components":{"minecraft:max_stack_size":"{{STACK_SIZE}}","minecraft:food":{"nutrition":0,"saturation_modifier":"low","can_always_eat":True,"effects":"{{POTION_EFFECTS}}"},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}}}}
ITEM_TEXTURE = {"resource_pack_name":"{{PACK_NAME}}","texture_name":"atlas.items","texture_data":{"{{ITEM_ID}}":{"textures":"textures/items/{{ITEM_ID}}"}}}
ARMOR_PIECE = {"format_version":"1.20.0","minecraft:item":{"description":{"identifier":"{{NAMESPACE}}:{{ITEM_ID}}","category":"Equipment"},"components":{"minecraft:max_stack_size":1,"minecraft:durability":{"max_durability":"{{DURABILITY}}"},"minecraft:armor":{"protection":"{{PROTECTION}}"},"minecraft:enchantable":{"value":10,"slot":"armor_{{SLOT}}"},"minecraft:wearable":{"slot":"slot.armor.{{SLOT}}","protection":"{{PROTECTION}}"},"minecraft:icon":{"texture":"{{ITEM_ID}}"},"minecraft:display_name":{"value":"{{DISPLAY_NAME}}"}}}}
HOSTILE = {"format_version":"1.19.0","minecraft:entity":{"description":{"identifier":"{{NAMESPACE}}:{{ENTITY_ID}}","is_spawnable":True,"is_summonable":True,"is_experimental":False},"components":{"minecraft:type_family":{"family":["{{ENTITY_ID}}","monster"]},"minecraft:health":{"value":"{{HEALTH}}","max":"{{HEALTH}}"},"minecraft:attack":{"damage":"{{DAMAGE}}"},"minecraft:movement":{"value":"{{SPEED}}"},"minecraft:navigation.walk":{"can_path_over_water":False},"minecraft:behavior.nearest_attackable_target":{"priority":2,"within_radius":"{{ATTACK_RADIUS}}","entity_types":[{"filters":{"test":"is_family","subject":"other","value":"player"},"max_dist":"{{ATTACK_RADIUS}}"}]},"minecraft:behavior.melee_attack":{"priority":3},"minecraft:behavior.random_stroll":{"priority":6,"speed_multiplier":1.0},"minecraft:behavior.look_at_player":{"priority":7,"look_distance":8},"minecraft:physics":{},"minecraft:pushable":{"is_pushable":True,"is_pushable_by_piston":True},"minecraft:collision_box":{"width":"{{WIDTH}}","height":"{{HEIGHT}}"},"minecraft:nameable":{},"minecraft:loot":{"table":"loot_tables/entities/{{ENTITY_ID}}.json"},"minecraft:despawn":{"despawn_from_distance":{"max_distance":128}}}}}
PASSIVE = {"format_version":"1.19.0","minecraft:entity":{"description":{"identifier":"{{NAMESPACE}}:{{ENTITY_ID}}","is_spawnable":True,"is_summonable":True,"is_experimental":False},"components":{"minecraft:type_family":{"family":["{{ENTITY_ID}}","animal"]},"minecraft:health":{"value":"{{HEALTH}}","max":"{{HEALTH}}"},"minecraft:movement":{"value":"{{SPEED}}"},"minecraft:navigation.walk":{"can_path_over_water":False},"minecraft:behavior.random_stroll":{"priority":6,"speed_multiplier":1.0},"minecraft:behavior.look_at_player":{"priority":7,"look_distance":8},"minecraft:behavior.panic":{"priority":1,"speed_multiplier":1.5},"minecraft:physics":{},"minecraft:collision_box":{"width":"{{WIDTH}}","height":"{{HEIGHT}}"},"minecraft:nameable":{},"minecraft:loot":{"table":"loot_tables/entities/{{ENTITY_ID}}.json"},"minecraft:despawn":{"despawn_from_distance":{"max_distance":128}}}}}
COMPANION = {"format_version":"1.19.0","minecraft:entity":{"description":{"identifier":"{{NAMESPACE}}:{{ENTITY_ID}}","is_spawnable":True,"is_summonable":True,"is_experimental":False},"component_groups":{"{{NAMESPACE}}:tamed":{"minecraft:behavior.follow_owner":{"priority":2,"speed_multiplier":1.2,"start_distance":10,"stop_distance":2},"minecraft:behavior.owner_hurt_by_target":{"priority":1}},"{{NAMESPACE}}:wild":{"minecraft:behavior.random_stroll":{"priority":6}}},"components":{"minecraft:type_family":{"family":["{{ENTITY_ID}}"]},"minecraft:health":{"value":"{{HEALTH}}","max":"{{HEALTH}}"},"minecraft:attack":{"damage":"{{DAMAGE}}"},"minecraft:movement":{"value":"{{SPEED}}"},"minecraft:tameable":{"probability":"{{TAME_CHANCE}}","tame_items":"{{TAME_ITEM}}","tame_event":{"event":"{{NAMESPACE}}:on_tame","target":"self"}},"minecraft:navigation.walk":{"can_path_over_water":True},"minecraft:physics":{},"minecraft:collision_box":{"width":"{{WIDTH}}","height":"{{HEIGHT}}"},"minecraft:nameable":{}},"events":{"{{NAMESPACE}}:on_tame":{"remove":{"component_groups":["{{NAMESPACE}}:wild"]},"add":{"component_groups":["{{NAMESPACE}}:tamed"]}}}}}
ENTITY_CLIENT = {"format_version":"1.10.0","minecraft:client_entity":{"description":{"identifier":"{{NAMESPACE}}:{{ENTITY_ID}}","materials":{"default":"entity_alphatest"},"textures":{"default":"textures/entity/{{ENTITY_ID}}"},"geometry":{"default":"geometry.{{ENTITY_ID}}"},"render_controllers":["controller.render.{{ENTITY_ID}}"],"spawn_egg":{"base_color":"{{EGG_COLOR_1}}","overlay_color":"{{EGG_COLOR_2}}"}}}}
RENDER_CONTROLLER = {"format_version":"1.10.0","render_controllers":{"controller.render.{{ENTITY_ID}}":{"geometry":"geometry.{{ENTITY_ID}}","materials":[{"*":"material.default"}],"textures":["texture.default"]}}}
RECIPE_SHAPED = {"format_version":"1.17","minecraft:recipe_shaped":{"description":{"identifier":"{{NAMESPACE}}:recipe_{{ITEM_ID}}"},"tags":["crafting_table"],"pattern":"{{PATTERN}}","key":"{{KEY}}","result":{"item":"{{NAMESPACE}}:{{ITEM_ID}}","count":"{{RESULT_COUNT}}"}}}
RECIPE_SHAPELESS = {"format_version":"1.17","minecraft:recipe_shapeless":{"description":{"identifier":"{{NAMESPACE}}:recipe_{{ITEM_ID}}"},"tags":["crafting_table"],"ingredients":"{{INGREDIENTS}}","result":{"item":"{{NAMESPACE}}:{{ITEM_ID}}","count":"{{RESULT_COUNT}}"}}}
RECIPE_FURNACE = {"format_version":"1.17","minecraft:recipe_furnace":{"description":{"identifier":"{{NAMESPACE}}:furnace_{{ITEM_ID}}"},"tags":["furnace","smoker","blast_furnace"],"input":"{{INPUT_ITEM}}","output":"{{NAMESPACE}}:{{ITEM_ID}}"}}
LOOT_TABLE = {"pools":[{"rolls":{"min":"{{MIN_ROLLS}}","max":"{{MAX_ROLLS}}"},"entries":"{{LOOT_ENTRIES}}"}]}
